# Keep app launches consistent with the workspace layout.
windowrule = workspace 2 silent, match:class ^(chromium)$
windowrule = workspace 4 silent, match:class ^(chromium)$, match:title .*Calendar.*
windowrule = workspace 4 silent, match:class ^(chromium)$, match:title .*Gmail.*
windowrule = workspace 5 silent, match:class ^(signal)$
windowrule = workspace 5 silent, match:class ^(TelegramDesktop|telegram-desktop|telegram|org\.telegram\.desktop)$
windowrule = workspace 6 silent, match:class ^(chromium)$, match:title .*WhatsApp.*
windowrule = workspace 6 silent, match:class ^(chromium)$, match:title .*X.*
